[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/stockfish.js"
  [headers.values]
    Content-Type = "application/javascript"
